stages:
  - before
  - test
  - after
rvm:
  - 2.3
  - 2.4
jobs:
  include:
    - stage: before
    - stage: after
  allow_failures:
    - rvm: 2.3
script: "if [\"$(ruby -v)\" =~ 2.3]; then; /bin/false; else; /bin/true; fi"
