script: true
notifications:
  email: false

matrix:
  include:
    - stage: one
      script: /bin/true
    - stage: one
      script: /bin/true
    - stage: two
      script: /bin/true
    - stage: two
      script: /bin/false
    - stage: three
      script: /bin/true
    - stage: three
      script: /bin/true
