sudo: false
notifications:
  email: false

cache: bundler

jobs:
  include:
    - stage: precache
      script: true
    - stage: test
      script: bundle show
    - stage: test
      script: bundle show
      
