stages:
  - name: deploy
    if: >-
        tag =~ ^(0|[1-9]\d*)(?:\.(0|[1-9]\d*))?(?:\.(0|[1-9]\d*))?(?:-([\w.-]+))?(?:\+([\w.-]+))?$ AND
        type IN (push, api)

jobs:
  include:
    - stage: test
      script: echo test
    - stage: deploy
      script: echo deploy
