script: true
notifications:
  email: false

matrix:
  include:
    - stage: one
      script: echo "First job on stage one!"
    - stage: one
      script: echo "Second job on stage one!"
    - stage: two
      script: echo "First job on stage two!"
