sudo: false
dist: trusty

notifications:
  email: false

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server      

script:
  - "mysql --version || true"
  - "dpkg -l 'mysql-server*' || true"
