matrix:
  include:
  - sudo: required
    os: linux
    dist: trusty
    env: QUEUE=gce DIST=trusty
  - sudo: required
    os: linux
    dist: precise
    env: QUEUE=gce DIST=precise
  - sudo: false
    os: linux
    dist: trusty
    env: QUEUE=ec2 DIST=trusty
install: true
script: true
