sudo: false
dist: trusty

notifications:
  email: false

jobs:
  include:
    - script: echo 1
    - script: echo 2
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        app: sf-stages-staging
        api_key: $HEROKU_AUTH_TOKEN
        on: sf-stages-demo
    - script: echo 3
