sudo: false
dist: trusty
# os: osx

script: 
    - echo $SECRET_1
    - echo $SECRET_2
    - bash ./wat

notifications:
  email: false
  webhooks: https://requestb.in/19c85fe1
  slack:
    secure: btlf2qSRkCl7qQw+Z9ORkmQjou6TS13cNqZMF+gO+i439+aHy5ffIFEvKZjUMD/XKNtMM3trn4oI4vV0UkWrWoqHIYsIq9EVXuJ/2HoeHtud6scWml0+or04tyE+rcz2DqeWOzGUZnciKWEOO9BxLGZH6kzmsDAOuvFqTJtuJ2b1WX7BzIA/9c/AwoUqh2CYt3ax7CT6VRoJnIzxTYHNadKJcjR4+Y4cbFDxteW5QuJJBdxyFiy11L7a9MS6WaE+resqdkjHyacgA0ICPyZCBm6Gr81DC8tiBZjrVVbB/wT0aCpZLaUuwyDbBSNpKFYcr15YjZkJgHtJ8q34gSWr//iqmCpL7s3h1jNzid9OVw/GXzxTvZYljUkEHv6boqc4qSV8eoncvgAXOa4J4d8ltvUj8rQriLXoc4ukkSm2HyPSFSYvRn+xKp0zIRU2tj6H/nKSPSENN1X9j49Fj324RVq4+GrnKlYS2i0JC0lFJtmrFW4A4Z0p3AG68zoBFOpQqIbH5fnTyFPkux+kH4qcAX8BSu/4t3D3bxdm8Yr5tfCAPwcupItfgzJZD8jAYGlxlVjRxakKmcCVVGB/C9lWDcTyujd9R4W7WGrL9RIOXfSHCStymCNeHPjRrbeCO8QdomZpKlJMAFbsv+gk/rx/Zsd14qk//fyB98O70d25jak=
