stages:
  - name: deploy
    if: branch = wat

jobs:
  include:
    - stage: compile
      script: echo compile
    - stage: test
      script: echo test
    - stage: deploy
      script: echo deploy
