dist: trusty
sudo: false

notifications: 
  email: false
 
jobs:
  include:
    - script: true
      rvm: 2.3
      stage: one
    - script: true
      rvm: 2.4
      stage: one
    - script: true
      stage: two
  allow_failures:
    - rvm: 2.3
