# wa{t::kaputt?^%!??

sudo: false
notifications:
  email: false

env:
  - FOO=foo
  - FOO=bar

script: echo $FOO

stages:
  - Compile
  - Test
  - Deploy

jobs:
  include:
    - stage: Compile
      script: echo Compile
    - stage: Deploy
      script: true
      deploy:
        <<: *heroku
        app: sf-stages-production
