language: ruby
dist: trusty
install: echo "true"
script: "echo secret: $MY_SECRET_ENV"
env:
  global:
    secure: E8LjcQq/ksvjy8eg5muCInAIYjA2J16W4UZCItI2vWjGH0t+Nk9kg7hNKvpZEZY02Kdb5QnmMPuHE/hAtvchzaeVFvOXHk99lNGme2kIZHJQMJ20zz0CrOTUExApCMQjVBHsukk6Pp1RA8+fzHoWVnDPixnMNlZ6rPf5jAkqYZf8AF53M3L/H1bGCawxtjm4msy3T7zmoL8E0ttS9hZlVxqpKPedEF1B9/p0OA18GLaTLd/7OUkWIxsayY2gmXbcIPllUTtAsqbFklm6u6h7DXrWxSj0h26h0pb1Jq4GVXURulQiQpLtL2u4tm8GM1pKFilTxF45NiY2noBq9hX7WBkgicq7A080faG3pO63a29T00zP4FTieEG/pXPrE5mmsBv/EmwawqtVLNYgGfWjQsXOgcwjEVJzCVuTGMouuA41rnvzLxHEw2U3gCajLHY2jX2E9um03DQdqX0sPRDumsmKyyuKOg3mxnlgCtWp5LiI8g8AYPWNDhv+oKM5z/3q/BhaTYvJr7il6IwGMx04GASAXtlD3LGLzG+l/OZ9CGvDI9Us2abp9z0SJxrC4IxHx15g23QDtZQbAPh87mVQ9aKX3ZDNjZoKYOtOUxX9S8L5HNtj1Q15R67kgky2fpyNyDm7yYIqVKs/+fCTUZxER00XRNm5CDTsJRZ4FkhH7Hw=
